import Footer from "@/components/Footer";
import Navbar from "@/components/Navbar";
import { Toaster } from "react-hot-toast";
import "./globals.css";
import UserSyncProvider from "@/components/UserSyncProvider";

export const metadata = {
  title: "Loop Market",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html data-theme="light" lang="en">
      <body className="">
        <UserSyncProvider>
          <Navbar />
          {children}
          <Toaster position="top-right" />
          <Footer />
        </UserSyncProvider>
      </body>
    </html>
  );
}
