import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import { Toaster } from "react-hot-toast";

export const metadata = {
  title: "Loop Market",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
    data-theme="light"
      lang="en"
    >
      <body className=""> 
        <Navbar/>
        {children}
        <Toaster position="top-right" />
        <Footer/>
        </body>
    </html>
  );
}
